services:
  postgres:
    container_name: postgres-sql-sc
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - samuchat
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin-sc
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - samuchat
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped

networks:
  samuchat:
    driver: bridge

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local